### ISSUE TITLE
Support some form of slashing in subnet actor

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/ipc#102]
The SA (at the parent net) serves as the arbiter for slashing. For this we will implement a function SA.reportMisbehavior(PoM). This function receives a PoM and, if the complaint is valid, it slashes of the misbehaving validator's stake (for simplicity we can start with =1), which results in its exclusion from the validator set in the next update. The reporter receives a small reward for its contribution (e.g., a finder's fee of =0.05 of the slashed amount).

SA.reportMisbehavior(PoM) logic for punishing equivocations:

The following variables are available to the function: The reporter, the alleged offender, the misbehavior and the proof.

1.  Verify that PoM contains two valid signatures of _offender_.

-   The parameters for validating the signature should exist in the validator set

-   Make sure that the signed blocks/votes belong to the same slot in the same subnet. (ie, avoid false accusations due to "replay".)

3.  Slash the offender's stake by immediately. Possibly remove the offender from the validator set in the next update.

-   Optional: mark the identity of the validator and ban it from re-entering the validator set (perhaps removing the ban after a defined number of checkpoints). Clearly, the validator can use a new identity but it might be worth considering even so.

Reward the reporter with of the slashed amount

//cc @guy-goren

**Comment by guy-goren** [comment]
Regarding 

> Make sure that the signed blocks/votes belong to the same slot in the same subnet. (ie, avoid false accusations due to "replay".)

Going into the finer details, when considering votes in the same slot, one should also notice the votes are for the same "view/ballot number". This is to avoid false accusations due to possible view changes.
