### ISSUE TITLE
Simplification: remove the ability to contribute collateral at subnet creation

### ISSUE THREAD

**Issue by raulk** [consensus-shipyard/ipc#1142]
Currently, if value is sent when registering a new subnet, we record it as collateral contributed by the creator, who will now be enlisted as a validator in the network. While this might be useful in some situations, it can be achieved by performing both actions separately, in an atomic manner if needed, either through a Multicall contract or through a dedicated utility smart contract.

In other words, this feature is actually an aggregate of two other features, and therefore my view is that it can be dropped from the base protocol/mechanics in order to reduce complexity. As far as I know, it is not being actively used by any adopter at the current time. And this work https://github.com/consensus-shipyard/ipc/pull/1130 was forced to add extra complexity to sustain this feature as we added a new collateral asset kind.

---

We can apply the same simplification to circulating supply -- I would just drop this as a subnet creation parameter.

**Comment by cryptoAtwill** [comment]
@raulk are you referring to this [method](https://github.com/consensus-shipyard/ipc/blob/78443ea98b419598878c1c19aa97c8ef02c9ecb0/contracts/contracts/gateway/GatewayManagerFacet.sol#L33)?

When the subnet is registered, it does not forward the collateral?

**Comment by raulk** [comment]
Gathering user input in Slack: https://filecoinproject.slack.com/archives/C04U4GPK3QR/p1727254644064279

**Comment by raulk** [comment]
@cryptoAtwill I'm referring to the whole flow, which includes that method, but also stuff in LibSubnetActor and other places.

**Comment by LePremierHomme** [comment]
Here's the current flow:

* `registry.newSubnetActor()` spawns `new SubnetActorDiamond()`. no built-in funding/staking here
* `actor.preFund()` can then be used to fund pre bootstrap
* validators use `actor.join()` to stake pre bootstrap (or after). if bootstrap is triggered, both _total_ funding and _total_ stake are sent to gateway

So there's no association of the subnet creator as being a validator or the contributor of collateral.

**Comment by raulk** [comment]
Yep, this was definitely a misinterpretation from my end. Thanks for entertaining it, though!
