### ISSUE TITLE
Review ipc-cli gas parameters

### ISSUE THREAD

**Issue by raulk** [consensus-shipyard/ipc#1175]
Akave folks have pointed out that ipc-cli transactions against Filecoin mainnet (e.g. subnet creation, subnet join, fund) seem to remain queued for long. This could be due to us miscalculating gas parameters (concretely the gas fee cap or premium). Even though we calculate our values based on the data returned by the Eth RPC API, it's possible that our code is carrying Ethereum assumptions that work for Calibrationnet (due to it being mostly vacant), but not for Mainnet.

**Comment by raulk** [comment]
I would maybe start here:

https://github.com/consensus-shipyard/ipc/blob/9b4df00e01a0362b30ee62383f5e48412161336b/ipc/provider/src/manager/evm/manager.rs#L1283

And here:

https://github.com/consensus-shipyard/ipc/blob/9b4df00e01a0362b30ee62383f5e48412161336b/ipc/provider/src/manager/evm/manager.rs#L1332-L1342

**Comment by karlem** [comment]
https://github.com/filecoin-project/lotus/blob/master/node/impl/full/gas.go#L187
