### ISSUE TITLE
Enforce new base fee in mempool after gas market base fee update

### ISSUE THREAD

**Issue by cryptoAtwill** [consensus-shipyard/ipc#1183]
With the introduction of gas market, block gas limit and base fee rotation were introduced. However, there is a missing piece when the base fee is updated, it should be enforced in the mempool for message selections: i.e. message in mempool below the new base fee, should be deprioritised for message selection.

**Comment by cryptoAtwill** [comment]
There are two main solutions proposed:
- Give cometbft n * block_gas_limit or potentially -1 so that cometbft will feed more messages to fendermint and fendermint does the message selection instead. This is slightly difficult to determine what `n` should be and feeding more messages to fendermint could be wasteful.
- Make use of cometbft's priority in `check_tx`. Basically the txns with higher base fee are given higher priorities. At the same time, cometbft will have [recheck](https://docs.cometbft.com/v0.37/core/mempool) enabled so that priorities are not fixed. Ofc gas is just one factor of priority and priority calculation can be generalized.

Method 2 is preferred at the moment.

**Comment by sanderpick** [comment]
when you say,

> i.e. message in mempool below the new base fee, should be deprioritised for message selection.

do this imply that during time of zero network usage (zero block gas utilization), that a user could set `gas_fee_cap` to `0` and get free block space? this is an edge case but just curious what the intention is.

**Comment by cryptoAtwill** [comment]
@sanderpick zero network usage should not have cause base fee to 0, the current gas market actor has a `minimal_base_fee` setting that prevents this from happening. So even if a block is empty, there is no free ride.

**Comment by sanderpick** [comment]
cool, makes sense. so instead of "message in mempool below the new base fee, should be deprioritised for message selection", it should just be rejected / dropped

**Comment by cryptoAtwill** [comment]
@sanderpick Not sure if we should drop them, because base fee varies, so next block those txns might have reached the base fee requirement.

**Comment by sanderpick** [comment]
Hey @cryptoAtwill, how's this one coming?

**Comment by cryptoAtwill** [comment]
@sanderpick , the [PR](https://github.com/consensus-shipyard/ipc/pull/1185) is ok for review, despite many changes in the main.

**Comment by raulk** [comment]
Backing up a little so we are all on the same page. Our endgame is to exclude transactions from sequencing/execution whose gas fee cap is below the current base fee. Unfortunately, as of today we rely on CometBFTs managed mempool. While we intend to migrate to an owned mempool in the future, today ain't the day. So we have to use the (limited) levers that CometBFT gives us to achieve our endgame here.

When we validate a transaction (CheckTx) we inform CometBFT of the gas limit of that transaction. On a related note, CometBFT knows our block gas limit, and we keep it updated as the gas market decides to change that value.

Having this knowledge, when populating a block, CometBFT selects a bundle of candidate transactions that satisfy the current block gas limit. We are able to exclude transactions from that bundle, but we can't easily poll for "more" transactions if we end up excluding too many.

Luckily, CometBFT exposes a tx priority mechanism. Our chosen solution is to leverage that mechanism together with these priority heuristics:

1. Transactions below the current base fee are assigned -MIN priority, so they're the last ones to be chosen.
2. For transactions above the base fee, we prioritise linearly based on premium.

With this ranking, we can be certain that CometBFT has sent us eligible transactions first, and that if we exclude txs below the base fee, there won't be anything left in the mempool anyway.

Unfortunately, as @cryptoAtwill mentioned, this requires us to enable the `recheck` flag to reprioritise pending mpool transactions as blocks are committed. The good news is that this flag is already enabled by default, so unless folks have disabled it, they should not see a performance degradation relative to today.

**Comment by sanderpick** [comment]
thanks for the great explainer!
