### ISSUE TITLE
L2+ testing todos

### ISSUE THREAD

**Issue by cryptoAtwill** [consensus-shipyard/ipc#1223]
After an initial round of testing with L2+ feature, here is a list of todos to consider:
1. Adding a doc on who, how is invoking cross messages calls. Because there were some assumption/requirements not properly documented yet, all the components needed to ensure correct functioning.
2. Currently, there is missing a debug tool for cross message calls. It would be really helpful to have a tool, maybe external, that tracks the lifecycle of the cross network messages, i.e. where the message submitted, which subnet is the message now, is the message committed into the postbox and etc... This would help debug cross network message execution.
3. Checking `subnet.circSupply`. Not sure if this variable is tracked correctly. This value is [deducted](https://github.com/consensus-shipyard/ipc/blob/1585e1befe662d0671f99c945ba9cb019db554c3/contracts/contracts/gateway/router/CheckpointingFacet.sol#L151C16-L151C26) by `IPCEnvelop.value` regardless message type? But only [increased](https://github.com/consensus-shipyard/ipc/blob/1585e1befe662d0671f99c945ba9cb019db554c3/contracts/contracts/lib/LibGateway.sol#L254) (after bootstrap) when message is Transfer
4. There should be a debug tool to check if the message execution is successful or failed. If failed, should be possible to show the error.
5. Consistent way to encode `ret` bytes. The way that encodes the error is using [encodeWithSelector](https://github.com/consensus-shipyard/ipc/blob/7572a6aac3b47a30e4d2146dee02e201acb865de/contracts/contracts/lib/LibGateway.sol#L362), but for L2+ error is just [encode](https://github.com/consensus-shipyard/ipc/blob/1585e1befe662d0671f99c945ba9cb019db554c3/contracts/contracts/lib/LibGateway.sol#L452), it's kind of confusing for debugging to tell which decode method to use.
6. [Emit event in test](https://github.com/consensus-shipyard/ipc/blob/1585e1befe662d0671f99c945ba9cb019db554c3/contracts/test/integration/L2PlusSubnet.t.sol#L494) should be removed. Events should be emitted in actual code, not from test, otherwise the expect becomes useless.

**Comment by karlem** [comment]
1. 100% agree. I will work on it today.
2. I think we could use https://thegraph.com/cs/ for this
3. This looks like a bug. Will fix today.

**Comment by cryptoAtwill** [comment]
Because of https://github.com/consensus-shipyard/ipc/issues/1225, the current approach of [scanning events](https://github.com/consensus-shipyard/ipc/blob/1585e1befe662d0671f99c945ba9cb019db554c3/contracts/contracts/lib/LibGateway.sol#L638C38-L638C65) emitted from postbox will not work. There will be missing events.

**Comment by cryptoAtwill** [comment]
The nonce handling is incorrect. Only the first xnet message will work, subsequent ones will fail.

The scenario is sending **_TWO_** cross network message from L1 to L3. This is the first ever L1 topdown message, so for the cross message itself, the nonce is 0.

On L2, topdown finality will have the message [applied](https://github.com/consensus-shipyard/ipc/blob/1585e1befe662d0671f99c945ba9cb019db554c3/contracts/contracts/gateway/router/XnetMessagingFacet.sol#L30). It gets committed with [appliedNonce increase by 1](https://github.com/consensus-shipyard/ipc/blob/1585e1befe662d0671f99c945ba9cb019db554c3/contracts/contracts/lib/LibGateway.sol#L437). Then the committed message in postbox is [propagated](https://github.com/consensus-shipyard/ipc/blob/1585e1befe662d0671f99c945ba9cb019db554c3/contracts/contracts/gateway/router/XnetMessagingFacet.sol#L31). Internally it calls [commitValidatedCrossMessage](https://github.com/consensus-shipyard/ipc/blob/1585e1befe662d0671f99c945ba9cb019db554c3/contracts/contracts/lib/LibGateway.sol#L638C38-L638C65) and appliedNonce is [incremented again by 1](https://github.com/consensus-shipyard/ipc/blob/1585e1befe662d0671f99c945ba9cb019db554c3/contracts/contracts/lib/LibGateway.sol#L530). 

The overall effect is one xnet message from L1 to L3 will increase the applied nonce by 2.

**Comment by cryptoAtwill** [comment]
Potential double nonce increment. 

Similar to the above, the `appliedNonce` is incremented first [here](https://github.com/consensus-shipyard/ipc/blob/1585e1befe662d0671f99c945ba9cb019db554c3/contracts/contracts/lib/LibGateway.sol#L437). But subsequently, it also call `sendReceipt`. Internally, it will [increment](https://github.com/consensus-shipyard/ipc/blob/1585e1befe662d0671f99c945ba9cb019db554c3/contracts/contracts/lib/LibGateway.sol#L530) the `appliedNonce` by 1 as well. This will lead to one message increasing the nonce by 2.
