### ISSUE TITLE
Integrate fevm-contract-tests in CI

### ISSUE THREAD

**Issue by raulk** [consensus-shipyard/ipc#194]
[This contract suite](https://github.com/filecoin-project/fevm-contract-tests) was built from OpenZeppelin + other test cases, to validate functional correctness of the Filecoin EVM. The repo says Lotus, but it should work against any Ethereum JSON-RPC API, including the one offered by Fendermint. It can be easily repurposed and integrated in CI here to validate functional correctness of Fendermint.

**Comment by snissn** [comment]
consensus-shipyard/fevm-contract-tests ci is now passing on main.  A passing run can be seen here: 

https://github.com/consensus-shipyard/fevm-contract-tests/actions/runs/7507453913

1 remaining task is to: 

- [ ] integrate the above passing test suite into this repo (consensus-shipyard  /  ipc)

**Comment by raulk** [comment]
@snissn Check the logs from each task. They aren't actually running the tests they're supposed to.

**Comment by snissn** [comment]
Thank you @raulk for pointing that out to me! I am looking into the cause to generate a solution now
