### ISSUE TITLE
BURNT_FUNDS_ACTOR explanation

### ISSUE THREAD

**Issue by snissn** [consensus-shipyard/ipc#21]
address constant BURNT_FUNDS_ACTOR = address(99);

is address(99) special or just chosen to be any other burn address? Why not 0? 

Interpretation of 'BURNT_FUNDS_ACTOR' as an address constant (address(99)) requires explanation. Does this address signify a special use case within the IPC context?

**Comment by snissn** [comment]
Another benefit of using the 0x0 address is that there's standardized acceptance about how to measure the supply of a token by discounting anything owned by the 0x0 burn account (and the 0x29 etc burn account)

**Comment by aakoshh** [comment]
The IDs are coming from [ref-fvm](https://github.com/filecoin-project/builtin-actors/blob/81595c23411ef3a759325d539b0618f9aa5500a3/runtime/src/builtin/singletons.rs#L19-L30). The 0x0 address became the system actor ID.

**Comment by aakoshh** [comment]
There were apparently other expectations regarding 0x0 in https://github.com/consensus-shipyard/ipc-monorepo/issues/166 which lead to https://github.com/consensus-shipyard/fendermint/pull/409
