### ISSUE TITLE
UX: add a flag in config to determine if the role of the IPC agent in the subnet

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/ipc#242]
We should allow a way in the ipc-agent config to determine if you want to sync with a subnet as a validator or not. Right now, the ipc-agent daemon tries by default to start the checkpoint managers as soon as you are syncing with a subnet, leading in many cases to errors that may be confusing (there's nothing wrong with the operation of the agent, but we still show an error that may seem like everything is wrong!).

**Comment by jsoares** [comment]
Should we look into daemon-less operation for end-user cases? I realise this duality isn't necessarily straightforward to implement but, at least conceptually, a user who's not monitoring the subnet for checkpoints and that just wants to craft transactions and submit them to the corresponding subnet RPCs could do this via synchronous commands without a background daemon.

**Comment by adlrocha** [comment]
I definitely want to move towards this by having a `daemon`, an `sdk` (that users and applications can use to interact with IPC networks) and then a `cli` that leverages either the `sdk` or a daemon endpoint to perform the operations. This may require a slight re-architecture of the agent, but I think it can really improve the UX. I'll add it to my backlog and try to share a draft design of the changes.

**Comment by adlrocha** [comment]
It no longer applies since the latest refactor that removes the use of the agent.
