### ISSUE TITLE
`util eth-to-f4-addr` should write to stdout

### ISSUE THREAD

**Issue by mturilin** [consensus-shipyard/ipc#272]
I was trying to convert addresses using Unix pipes and was surprised that `util eth-to-f4-addr` doesn't write to stdout.

Here's a sample bash command:

```bash
cat evm_addresses.txt | while read line
do 
./ipc-agent/bin/ipc-agent util eth  -to-f4-addr --addr $line | tr -d '"' >> fvm_addresses.txt
done
```

It's not the end of the world, but I think it would be cool if we follow the standard UNIX convention for tools' output.

**Comment by mturilin** [comment]
The same suggestion for `ipc-agent wallet new`

**Comment by jsoares** [comment]
Agreed, this is a little weird. We're just logging the address:

https://github.com/consensus-shipyard/ipc-agent/blob/611a98988b612edd66c018ae282110aa568c848d/src/cli/commands/util/f4.rs#L22

I wonder if there's a reason to do it this way... Github says @adlrocha is to blame, so let's ask him.

**Comment by adlrocha** [comment]
Fixed.
