### ISSUE TITLE
Set permission mode and supply source from genesis

### ISSUE THREAD

**Issue by cryptoAtwill** [consensus-shipyard/ipc#496]
Currently the permission mode and supply source is set as default values, we should be able to set them from genesis json.

**Comment by cryptoAtwill** [comment]
This issue should no longer be needed as fendermint genesis creation of gateway and subnet registry no longer needs permission mode and supply source flags.

**Comment by cryptoAtwill** [comment]
`supply_source` and `permission_mode` are set in ipc-cli when creating subnet, which are already in place.

**Comment by raulk** [comment]
Should we remove these fields from the genesis data structure, then?

**Comment by cryptoAtwill** [comment]
@raulk I ran a quick scan in the source code, I dont see these two fields in anywhere except subnet creation params which it they should be there for testing. Do you have links to the data structure you mentioned?
