### ISSUE TITLE
Solidify this repo

### ISSUE THREAD

**Issue by raulk** [consensus-shipyard/ipc#512]
At last, the IPC codebase is in a monorepo -- and the build and CI both work! This issue tracks a bunch of follow-ups to solidify the structure and usage of this repo.

## Repos cleanup

- [x] Archive and deprecate old repos, adding a note in the README pointing to the monorepo.
  - [x] [https://github.com/consensus-shipyard/fvm-utils](https://github.com/consensus-shipyard/fvm-utils)
  - [x] [https://github.com/consensus-shipyard/ipc-solidity-actors](https://github.com/consensus-shipyard/ipc-solidity-actors)
  - [x] [https://github.com/consensus-shipyard/ipc-ipld-resolver](https://github.com/consensus-shipyard/ipc-ipld-resolver)
  - [x] [https://github.com/consensus-shipyard/ipc](https://github.com/consensus-shipyard/ipc) (rename to `ipc-libs` first, to free up the `ipc` name)
  - [x] [https://github.com/consensus-shipyard/fendermint](https://github.com/consensus-shipyard/fendermint)
- [x] Rename this repo to `ipc`.
- [x] Update the README of this repo.

## Build and CI

- [x] Restore the correct name for the Fendermint Docker image (`fendermint`).
- [x] Port the Ganache test job from ipc-solidity-actors here: [https://github.com/consensus-shipyard/ipc-solidity-actors/commit/bf36dba67ca30de03b5d671374bdb59cf27db6f6](https://github.com/consensus-shipyard/ipc-solidity-actors/commit/bf36dba67ca30de03b5d671374bdb59cf27db6f6) (this got added last minute and was not integrated here).
- [ ] ~~Ensure we're using caching all throughout (except when publishing?).~~

## Non-code reorg

- [x] Move infra scripts from inner modules to top-level `/infra` directory.
- [x] Move docs from inner modules to top-level `/docs` directory.

## Code reorg

> Here's a concrete code tree proposal, let's discuss in comments.

- [x] Done

```
/
|__ infra
|__ docs
|__ contracts
|__ cli # binary crate containing the ipc cli
|
|__ ipc
| |__ wallet # former ipc/identity; this is a wallet library containing keystores, key types, wallet, etc.; using the opportunity to adjust naming to be more descriptive
| |__ provider
| |__ api # former ipc/sdk; these contain external IPC API types; SDK tends to imply "developer SDK", which this isn't
| |__ types # former fvm-utils/primitives; these contain basic types; some may move to ipld/types (e.g. Hamt, Cid, etc.)
|
|__ ipld
| |__ resolver # ipld-resolver
|
|__ fendermint
| |__ abci
| |__ app
| |__ crypto
| |__ ...
|
|__ testing # former ipc/testing, to be refactored later
```

## Update infra scripts

Some infra scripts are outdated, e.g. the current `ipc/scripts/install_infra.sh` still clones fendermint. Need to figure these out in detail.

**Comment by raulk** [comment]
Test comment

**Comment by aakoshh** [comment]
> types # former fvm-utils/primitives; these contain basic types; some may move to ipld/types (e.g. Hamt, Cid, etc.)

I agree that they aren't `ipc` specific. Where to put this was exactly my question when I first suggested this in https://github.com/filecoin-project/builtin-actors/issues/489 

`ipld/types` sounds better to me, although we should clean up the error types to remove references to `fil_actor_runtime`, which was one of the reasons I never imported these, even though we could use it in `fendermint_vm_actor_interfaces` for example.

**Comment by fridrik01** [comment]
@raulk What do you mean with "Restore the correct name for the Fendermint Docker image"? Not sure I know exactly what that details

**Comment by jsoares** [comment]
>[consensus-shipyard/ipc](https://github.com/consensus-shipyard/ipc) (rename to ipc-libs first, to free up the ipc name)

Note that this will break old issue referencing (i.e. if there's something in `the new `ipc-monorepo` referencing `ipc#21`, GH won't be able to redirect and will instead link to a wrong issue). I agree it's the right thing to do, mind you, just something to keep in mind. If we really wanted to preserve this, we should rewrite references first, but it's probably not worth it.

Unrelated: I also went ahead and closed the old GitHub projects, given the move to Linear.
