### ISSUE TITLE
GMP: Couple checkpoints and bottom-up message batches again

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/ipc#529]
## Background

Before we had `Ack/Receipt` messages in IPC, coupling checkpoints and bottom-up message execution led to an issue where a checkpoint may not ever be submitted because one of the messages included in the batch fails. The fact that checkpoints and messages are executed and submitted in order respectively, meant that a failing checkpoint would prevent future checkpoints (and messages) from being executed, halting the ability for a subnet to be able to send cross-net messages.

By decoupling checkpoints and bottom-up messages we removed this issue and we started making baby steps towards an independent incentive model for messages and checkpoints, and to include the ability for relayers to submit batches of unordered transactions. With this decoupling, checkpoints could submit an inclusion proof-friendly data structure that would allow the gateway in the parent to identify if a message is included in a batch had been successfully committed in the child.

Unfortunately, we didn't tackle the full refactor leading to the current implementation where checkpoints and batches are not synced, and while checkpoint can't be halted, message batches could still halt because the committee that signed a batch may not be synced with the active membership in the parent, rejecting the batch.

## Proposal

As discussed in yesterday's sync, the most straightforward solution would be to couple bottom-up message batches again into checkpoints to piggy-back from the submission of checkpoints to execute message batches. Now, we won't halt checkpoint submission even if a message fails, because failing messages would increase the applied nonce, and propagate and ACK. The operation would be as follows:

* We create bottom-up batches as we currently do.
* When we reach the checkpoint period or the maximum number of messages in a batch is reached, a new checkpoint is created for propagation and signature. In the checkpoint, we include the CID of the batch (not the full batch) that a relayer can provide when submitting the checkpoint.
* `submitCheckpoint` in the parent, as before, commits the checkpoint and executes the batch.

> Note for the implementer: this is a merge of the current bottom-up message batch logic and the checkpoint submission logic,

## Future Work

After the Fluence sprint, we should consider exploring the unordered execution of bottom-up messages where:

* Checkpoints include an incremental data structure like a [Merkle Mountain Range (MMR)](https://github.com/mimblewimble/grin/blob/master/doc/mmr.md).
* Relayers can send any message for execution as long as it provides a valid inclusion proof against the MMR committed in a checkpoint at the parent.
* This would allow us to start building a gas model and incentives on top of these messages in the form of a `fee` and a `gas_limit`.

**Comment by raulk** [comment]
Merged to `main` in https://github.com/consensus-shipyard/ipc/pull/543.
