### ISSUE TITLE
GMP: Execution of `IpcEnvelope`

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/ipc#530]
- [x] Implementation of new data structures for `IpcEnvelope` and cross-net messages as described [here](https://www.notion.so/pl-strflt/General-Message-Passing-7686edb5b65c4f9086fa4d4288c35906?pvs=4#55294071dfd648c1ae6868a71db28fda)
- [x] Implementation of the new subnet actor and gateway methods required in the gateway to forward and trigger the execution of the `IpcEnvelope` as detailed [here](https://www.notion.so/pl-strflt/General-Message-Passing-7686edb5b65c4f9086fa4d4288c35906?pvs=4#5a98a85172f24e17b1526f014b34877e). Remember that the design still mentions the enforcement of firewall policies, but these are out of scope for the first iteration. Cross-net message ACLs are explicitly implemented as part of the IPC-enabled user smart contracts.

**Comment by raulk** [comment]
Merged to `main` in https://github.com/consensus-shipyard/ipc/pull/543.
