### ISSUE TITLE
GMP: `IpcContract` abstract contract and `IpcEntrypoint` core implementation

### ISSUE THREAD

**Issue by adlrocha** [consensus-shipyard/ipc#532]
Implement the abstract contract and common logic for all IPC-enabled contracts. This will be used as the "sdk" for contracts looking to support the execution of cross-net message. Design details [here](https://www.notion.so/pl-strflt/General-Message-Passing-7686edb5b65c4f9086fa4d4288c35906?pvs=4#8047dfc79bcb4e0cb8ea12f2e4fe2bdd).

**Comment by raulk** [comment]
Merged to `main` in https://github.com/consensus-shipyard/ipc/pull/543.
