### ISSUE TITLE
Bootstrap the integration testing framework

### ISSUE THREAD

**Issue by fridrik01** [consensus-shipyard/ipc#566]
See master task: https://github.com/consensus-shipyard/ipc/issues/565

Goal of this task is to write a few simple integration tests along with  initial builder/dsl for setting up the test, we can then share with the team for feedback, iterate on design before committing to more complex functionality.

Example tests:
- Run fendermint as root network (look at infra/fendermint/scripts/testnode.toml)
- Run and verify network has required IPC contracts

**Comment by aakoshh** [comment]
Just to note that Lotus as root works very differently than Fendermint as root. We haven't tried the latter, but the former has null blocks which gave a lot of trouble during syncing.
