### ISSUE TITLE
Staging: Automated deployment of `main` on a test environment against Calibnet

### ISSUE THREAD

**Issue by raulk** [consensus-shipyard/ipc#622]
## Goal

Build an automation that we can trigger manually to instantiate a new subnet on Calibnet and deploy a small dev network with 3-4 validators and one relayer on a hosted environment.

## Details

This should be a GitHub Action that we can trigger through the GitHub Actions UI. For now, we can deploy the network on a single machine, and have any new deployment kill and delete the previous instance. The team can coordinate off-band to redeploy.

Ideally, we'd deploy the Blockscout explorer alongside the devnet to gain easy visibility, just like we have for the [Mycelium Testnet](https://explorer.mycelium.calibration.node.glif.io/), but this can also come later.

This could be as simple as a shell/python script (whatever is fastest) that we call by ssh'ing into our host. The script would:

1. Kill and archive the previous deployment (as a first step we can delete if that would be simpler).
2. Create the subnet in Calibnet. For this we will need to have a wallet with topped up with sufficient balance. @maciejwitowski can help securing Calibnet funds. We'd configure the privkey of this wallet in the script.
3. Instantiate the validators, bootstrappers, etc. 
4. Instantiate the relayer.
5. Spin up a Blockscout instance (can come later).

➡️  See https://github.com/consensus-shipyard/ipc/blob/main/docs/ipc/quickstart-calibration.md for the full set of steps required to launch a subnet.

The GitHub Action would spit out the RPC URL and the SubnetID, amongst other useful details.

Ideally we'd build this in a way that is _not_ coupled with the GitHub Action, so that anyone can run it to quickly spin up a local subnet devnet against Calibnet.

**Comment by maciejwitowski** [comment]
Can we make the branch configurable in case we want to ship something different than `main`? (testing on feature branch or fallback on a stable commit as a Mycelium fallback for the hackathon).

**Comment by raulk** [comment]
Sure.
