### ISSUE TITLE
Build warnings for fendermint_actors

### ISSUE THREAD

**Issue by jsoares** [consensus-shipyard/ipc#829]
```
   Compiling fendermint_actors v0.1.0 (/home/ubuntu/ipc/fendermint/actors)
warning: fendermint_actors@0.1.0: out_dir: "/home/ubuntu/ipc/target/release/build/fendermint_actors-5bb6e52664b572e7/out/bundle"
warning: fendermint_actors@0.1.0: cmd=env -u CARGO_ENCODED_RUSTFLAGS CARGO_TARGET_DIR="/home/ubuntu/ipc/target/release/build/fendermint_actors-5bb6e52664b572e7/out/bundle" "/home/ubuntu/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/cargo" "build" "-p=fendermint_actor_chainmetadata" "-p=fendermint_actor_eam" "--target=wasm32-unknown-unknown" "--profile=wasm" "--features=fil-actor" "--manifest-path=/home/ubuntu/ipc/fendermint/actors/Cargo.toml"
warning: fendermint_actors@0.1.0: "   Compiling fendermint_actor_eam v0.1.0 (/home/ubuntu/ipc/fendermint/actors/eam)"
warning: fendermint_actors@0.1.0: "    Finisheadded chainmetd wasm [optimized] target(s) in 3.07s"
warning: fendermint_actors@0.1.0: adata (1) to bundle with CID bafk2bzacedjcuuzna7xla3qffpqrl4x7mgsybdmi5bra4mjtvhoqimdywrsyk
warning: fendermint_actors@0.1.0: added eam (2) to bundle with CID bafk2bzacedvs2i7kth7zz4d4l2qinbw4mo5wlvkgalxl76qbapynq5hrzxmey
warning: fendermint_actors@0.1.0: bundle=output/custom_actors_bundle.car
```

The actor build process logs a number of warnings -- all the `cargo:warning` entries in [https://github.com/consensus-shipyard/ipc/blob/main/fendermint/actors/build.rs#L115](https://github.com/consensus-shipyard/ipc/blob/main/fendermint/actors/build.rs#L115).

@fridrik01 do we need to keep these (gh blames you)?

**Comment by jsoares** [comment]
That might still be the case, from quick research, but why do we need to output this information? I can imagine the CIDs being relevant --maybe-- but I have a harder time coming up with a reason to print the commands, paths, and compilation times.

**Comment by raulk** [comment]
It has proven useful in the past, that's why we added it and it has remained useful in builtin-actors. These Wasm builds can be slow depending on the actor and there is no sign of progress unless you print something to the console. The CIDs are also useful for debugging. These warnings are harmless and they have not affected any tooling, so unless there's a more convincing reason to remove them, I don't see the ROI of removing them.

**Comment by jsoares** [comment]
I find it poor practice to pollute build logs with spurious warnings, but hardly the end of the world.
