### ISSUE TITLE
Support Eth legacy transactions

### ISSUE THREAD

**Issue by maciejwitowski** [consensus-shipyard/ipc#927]

**Comment by raulk** [comment]
---

We only support legacy transactions partially for estimation purposes:

https://github.com/consensus-shipyard/ipc/blob/ebb743f42882efa7af8f4a31970e9c854893238b/fendermint/eth/api/src/conv/from_eth.rs#L20

---

This is how Filecoin bolted on Eth legacy tx support recently:

https://github.com/filecoin-project/FIPs/blob/master/FIPS/fip-0091.md

---

This is needed to deploy things like Gnosis Safe on IPC subnets; unfortunately legacy transactions are quite ossified in some libraries / tools.
