### ISSUE TITLE
JSON-RPC: record and export request latency as a Prometheus metric

### ISSUE THREAD

**Issue by raulk** [consensus-shipyard/ipc#943]
This should be as simple as enhancing the `with_methods!` macro to measure the latency and record it under a Prometheus histogram.

Notes:
* Don't forget to expose the Prometheus registry within the `fendermint eth run` command (it may already be exposed).
* Add the histogram metric here: https://github.com/consensus-shipyard/ipc/blob/147180ce386c9d950d04dcbad2a6ca19e3a1ff60/fendermint/app/src/metrics/prometheus.rs#L46

**Comment by karlem** [comment]
Close - implemented here: https://github.com/consensus-shipyard/ipc/pull/1045
